= Notices for HTTP Messages Signing

This content is produced and maintained by Mikaël Barbero and other contributors.

* Project home: https://github.com/mbarbero/http-messages-signing

== Trademarks

Eclipse Dash, Tools for Committers, and Dash, Tools for Committers are
trademarks of the Eclipse Foundation. Eclipse, and the Eclipse Logo are
registered trademarks of the Eclipse Foundation.

== Declared Project Licenses

This program and the accompanying materials are made available under the terms 
of the Eclipse Public License 2.0 which is available at 
https://www.eclipse.org/legal/epl-2.0/

SPDX-License-Identifier: EPL-2.0

== Source Code

The project maintains the following source code repository:

 * https://github.com/mbarbero/http-messages-signing.git

== Dependencies

=== Apache HttpComponents Core (4.x)

 * License: Apache License, 2.0
 * Project: https://hc.apache.org/httpcomponents-core-ga/index.html
 * Source: https://hc.apache.org/downloads.cgi

=== OkHttp3 (3.x)

 * License: Apache License, 2.0
 * Project: http://square.github.io/okhttp/
 * Source: https://github.com/square/okhttp

=== Google Guava (24)

 * License: Apache License, 2.0
 * Project: https://github.com/google/guava

=== Javax Servlet (3.x, 4.x)

 * License: Common Development and Distribution License (CDDL), 1.1
 * Project: https://github.com/javaee/servlet-spec

=== Junit (5.0.x)

 * License: Eclipse Public License, 2.0
 * Project: https://junit.org/junit5/
 * Source: https://github.com/junit-team/junit5/

==== Junit Platform Surefire Provider (1.0.x)

 * License: Apache License, 2.0
 * Project: https://junit.org/junit5/
 * Source: https://github.com/junit-team/junit5/

== Cryptography

Content may contain encryption software. The country in which you are currently
may have restrictions on the import, possession, and use, and/or re-export to
another country, of encryption software. BEFORE using any encryption software,
please check the country's laws, regulations and policies concerning the import,
possession, or use, and re-export of encryption software, to see if this is
permitted.