= HTTP Message Signing

image:https://travis-ci.org/mbarbero/http-messages-signing.svg?branch=master["Build Status", link="https://travis-ci.org/mbarbero/http-messages-signing"]
image:https://img.shields.io/badge/license-EPL--2.0-blue.svg["License", link="https://opensource.org/licenses/EPL-2.0"]
image:https://img.shields.io/maven-central/v/tech.barbero.http-messages-signing/http-messages-signing-core.svg[Maven Central]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/tech.barbero.http-messages-signing/http-messages-signing-core.svg[Sonatype OSSRH (Snapshots)]

Java Implementation of the IETF draft for https://tools.ietf.org/html/draft-cavage-http-signatures-09[HTTP Message Signing]. It provides bridges with the following libraries:

* https://hc.apache.org[Apache HTTP Components 4.x]
* http://square.github.io/okhttp/[OkHttp 3.x]
* https://javaee.github.io/servlet-spec/[Java Servlet 3.x and 4.x]

== Recipes

=== Create a HTTP messages signer

[source,java]
----
HttpMessageSigner signer = HttpMessageSigner.builder()
		.algorithm(Algorithm.RSA_SHA256)
		.keyMap(keyMap)
		.addHeaderToSign(HttpMessageSigner.REQUEST_TARGET)
		.addHeaderToSign("Date")
		.addHeaderToSign("Content-Length")
		.addHeaderToSign("Digest")
		.keyId("myKeyId")
		.build();
----

=== Signing an Apache HttpCore request 

[source,java]
----
HttpClientBuilder builder = HttpClientBuilder.create();
builder.addLast(new RequestSignature(signer));
try (CloseableHttpClient client = builder.build()) {
	HttpGet httpget = new HttpGet(uri);
	try (CloseableHttpResponse response = httpclient.execute(httpget)) {
		...
	}
}
----

=== Signing an OkHttp request

[source,java]
----
OkHttpClient client = new OkHttpClient.Builder()
		.addInterceptor(new SignerInterceptor(signer))
		.build();

Request request = new Request.Builder()
		.url(url)
		.build();

try (Response response = client.newCall(request).execute()) {
	...
}
----

== Requirements

Java 8

== Build

[source,sh]
----
$ mvn clean install
----

== Documentation 

Javadoc can be be found at https://mbarbero.github.io/http-messages-signing/apidocs/1.0.0-SNAPSHOT/

== About

Copyright (c) 2017-2018 Eclipse Foundation and others.

Eclipse and the Eclipse logo are registered trademarks of The Eclipse Foundation.

Java and all Java-based trademarks are trademarks of Oracle Corporation in the United States, other countries, or both.

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/

Content may contain encryption software. The country in which you are currently may have restrictions on the import, possession, and use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check the country’s laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted.
