= HTTP Message Signing

image:https://travis-ci.org/mbarbero/http-messages-signing.svg?branch=master["Build Status", link="https://travis-ci.org/mbarbero/http-messages-signing"]

Java Implementation of the IETF draft for https://tools.ietf.org/html/draft-cavage-http-signatures-09[HTTP Message Signing]. It provides bridges with the following libraries:

* https://hc.apache.org[Apache HTTP Components 4.x]
* http://square.github.io/okhttp/[OkHttp 3.x]
* https://javaee.github.io/servlet-spec/[Java Servlet 3.x and 4.x]

== Requirements

Java 8

== Build

[source,sh]
----
$ mvn clean install
----

== About

Copyright (c) 2017-2018 Eclipse Foundation and others.

Eclipse and the Eclipse logo are registered trademarks of The Eclipse Foundation.

Java and all Java-based trademarks are trademarks of Oracle Corporation in the United States, other countries, or both.

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/

Content may contain encryption software. The country in which you are currently may have restrictions on the import, possession, and use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check the country’s laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted.
