= HTTP Message Signing

image:https://travis-ci.org/mbarbero/http-messages-signing.svg?branch=master["Build Status", link="https://travis-ci.org/mbarbero/http-messages-signing"]
image:https://img.shields.io/badge/license-EPL--2.0-blue.svg["License", link="https://opensource.org/licenses/EPL-2.0"]
image:https://img.shields.io/maven-central/v/tech.barbero.http-messages-signing/http-messages-signing-core.svg[Maven Central, link="https://repo1.maven.org/maven2/tech/barbero/http-messages-signing/"]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/tech.barbero.http-messages-signing/http-messages-signing-core.svg[Sonatype OSSRH (Snapshots), link="https://oss.sonatype.org/content/repositories/snapshots/tech/barbero/http-messages-signing/"]
image:https://sonarcloud.io/api/project_badges/measure?project=tech.barbero.http-messages-signing%3Ahttp-messages-signing-parent&metric=alert_status[SonarQube Analysis, link="https://sonarcloud.io/dashboard?id=tech.barbero.http-messages-signing%3Ahttp-messages-signing-parent"]

Java Implementation of the IETF draft for https://tools.ietf.org/html/draft-cavage-http-signatures-09[HTTP Message Signing]. It provides bridges with the following libraries:

* https://hc.apache.org[Apache HTTP Components 4.x]
* http://square.github.io/okhttp/[OkHttp 3.x]
* https://javaee.github.io/servlet-spec/[Java Servlet 3.x and 4.x]

== Latest release

The most recent release is http-messages-signing 1.0.0, released 2018-02-20 and available on Maven central. https://mbarbero.github.io/http-messages-signing/apidocs/1.0.0/[Javadoc is available].

To add a dependency on http-messages-signing using Maven, use the following:

[source,xml]
----
<dependency>
  <groupId>tech.barbero.http-messages-signing</groupId>
  <artifactId>http-messages-signing-core</artifactId>
  <version>1.0.0</version>
</dependency>
----

To add a dependency using Gradle:

[source,gradle]
----
dependencies {
  compile 'tech.barbero.http-messages-signing:http-messages-signing:1.0.0'
}
----

And one of the bridge if required.

=== Apache HTTP Component 4.x

[source,xml]
----
<dependency>
  <groupId>tech.barbero.http-messages-signing</groupId>
  <artifactId>http-messages-signing-ahc4</artifactId>
  <version>1.0.0</version>
</dependency>
----

[source,gradle]
----
dependencies {
  compile 'tech.barbero.http-messages-signing:http-messages-signing-ahc4:1.0.0'
}
----

=== OkHttp 3.x

[source,xml]
----
<dependency>
  <groupId>tech.barbero.http-messages-signing</groupId>
  <artifactId>http-messages-signing-okhttp3</artifactId>
  <version>1.0.0</version>
</dependency>
----

[source,gradle]
----
dependencies {
  compile 'tech.barbero.http-messages-signing:http-messages-signing-okhttp3:1.0.0'
}
----

=== Servlet 3.x, 4.x

[source,xml]
----
<dependency>
  <groupId>tech.barbero.http-messages-signing</groupId>
  <artifactId>http-messages-signing-servlet</artifactId>
  <version>1.0.0</version>
</dependency>
----

[source,gradle]
----
dependencies {
  compile 'tech.barbero.http-messages-signing:http-messages-signing-servlet:1.0.0'
}
----

== Snapshots

Snapshots of http-messages-signing built from the master branch are available on https://oss.sonatype.org/content/repositories/snapshots[Sonatype Snapshot Repository]. https://mbarbero.github.io/http-messages-signing/apidocs/1.0.1-SNAPSHOT/[Javadoc is available].

== Recipes

=== Create a HTTP messages signer

[source,java]
----
HttpMessageSigner signer = HttpMessageSigner.builder()
		.algorithm(Algorithm.RSA_SHA256)
		.keyMap(keyMap)
		.addHeaderToSign(HttpMessageSigner.REQUEST_TARGET)
		.addHeaderToSign("Date")
		.addHeaderToSign("Content-Length")
		.addHeaderToSign("Digest")
		.keyId("myKeyId")
		.build();
----

=== Signing an Apache HttpCore request 

[source,java]
----
HttpClientBuilder builder = HttpClientBuilder.create();
builder.addLast(new RequestSignature(signer));
try (CloseableHttpClient client = builder.build()) {
	HttpGet httpget = new HttpGet(uri);
	try (CloseableHttpResponse response = httpclient.execute(httpget)) {
		...
	}
}
----

=== Signing an OkHttp request

[source,java]
----
OkHttpClient client = new OkHttpClient.Builder()
		.addInterceptor(new SignerInterceptor(signer))
		.build();

Request request = new Request.Builder()
		.url(url)
		.build();

try (Response response = client.newCall(request).execute()) {
	...
}
----

== Requirements

Java 8

== Build

[source,sh]
----
$ mvn clean install
----

== About

Copyright (c) 2017-2018 Eclipse Foundation and others.

Eclipse and the Eclipse logo are registered trademarks of The Eclipse Foundation.

Java and all Java-based trademarks are trademarks of Oracle Corporation in the United States, other countries, or both.

This program and the accompanying materials are made available under the terms of the Eclipse Public License 2.0 which is available at https://www.eclipse.org/legal/epl-2.0/

Content may contain encryption software. The country in which you are currently may have restrictions on the import, possession, and use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check the country’s laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted.
